### PR TITLE
Working ram

### PR DESCRIPTION
**Pull request by RamRS**
These are changes that override the changes from the previous commit/pull-request. Changes have been made in the way objects are pickled and unpickled, and also in the use of CMD line args.
## 

Ram

### CODE REVIEW

**Comment by ctb** [comment]
Please push these onto the same branch as the previous pull request, and close this one. Tx.

---

C. Titus Brown, ctb@msu.edu

**Comment by RamRS** [comment]
That has an open pull request, closing it and replacing with new pull
request...

## 

Ram

**Comment by RamRS** [comment]
New pr created comparing master branches, closing this pr.

**Comment by ctb** [comment]
In case it's not clear, you just keep on updating the branch.  This can
include reverting the branch to previous versions manually (that is,
not undoing the commits, but overwriting the commits with older versions
of the file).

On Sun, Aug 25, 2013 at 03:15:28PM -0700, Ram RS wrote:

> That has an open pull request, closing it and replacing with new pull
> request...
> 
> ## 
> 
> Ram
> 
> On Sun, Aug 25, 2013 at 5:43 PM, C. Titus Brown notifications@github.comwrote:
> 
> > Please push these onto the same branch as the previous pull request, and
> > close this one. Tx.
> > 
> > ---
> > 
> > C. Titus Brown, ctb@msu.edu
> > 
> > On Aug 25, 2013, at 17:21, Ram RS notifications@github.com wrote:
> > 
> > > These are changes that override the changes from the previous
> > > commit/pull-request. Changes have been made in the way objects are pickled
> > > and unpickled, and also in the use of CMD line args.
> > > 
> > > Ram
> > > 
> > > You can merge this Pull Request by running
> > > 
> > > git pull https://github.com/RamRS/eel-pond working-ram
> > > Or view, comment on, or merge it at:
> > > 
> > > https://github.com/ctb/eel-pond/pull/6
> > > 
> > > Commit Summary
> > > 
> > > Modified namedb.py and annotate-seqs.py to work with files supplied via
> > > command line to annotate-seqs.py
> > > Modified annotate-seqs, make-namedb and namedb to work on custom seq
> > > File Changes
> > > 
> > > M annotate-seqs.py (8)
> > > M make-namedb.py (9)
> > > M namedb.py (8)
> > > Patch Links:
> > > 
> > > https://github.com/ctb/eel-pond/pull/6.patch
> > > https://github.com/ctb/eel-pond/pull/6.diff
> > 
> > ???
> > Reply to this email directly or view it on GitHubhttps://github.com/ctb/eel-pond/pull/6#issuecomment-23236172
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ctb/eel-pond/pull/6#issuecomment-23236608

## 

C. Titus Brown, ctb@msu.edu

**Comment by RamRS** [comment]
Yes, makes much more sense. The prs opened for khmer-protocols and eel-pond will now stay open and I'll just push new commits as they happen!

**Pull request closed without merging**
